### ISSUE TITLE
New issue since 23/12/2016 - Certainly changes on the servers from La Banque Postale

### ISSUE THREAD

**Issue by testcocoon** [pixel/perl-finance-bank-laposte#6]
Here is the error that I have:
```
getting https://voscomptesenligne.labanquepostale.fr/wsost/OstBrokerWeb/loginform/../loginform?imgid=allunifie2&e=4&0.1498881563110227 failed
<html>
<head><title>An Error Occurred</title></head>
<body>
<h1>An Error Occurred</h1>
<p>500 Internal Server Error</p>
</body>
</html>
```
I guess that la Banque Postale was changing some URL because my script was working since one year without any changes. The errors occurs since 23/12/2016.

**Comment by prigaux** [comment]
Please try with latest commit  fd790ba4b08eea0876b00db1aa8dc9ff3b0fa45c on master.
It seems to fix it (not tested much though, i'm away...)

**Comment by testcocoon** [comment]
It works. I think that you can publish this fix.
Thanks.
Sébastien

**Comment by prigaux** [comment]
Cool. I've uploaded 7.11 to cpan.
