### ISSUE TITLE
Connection broken

### ISSUE THREAD

**Issue by testcocoon** [pixel/perl-finance-bank-laposte#7]
Since two days the connection to the site of La Banque Postale is broken.
I did not investigate it but I guess that they change their login mechanism.

**Comment by prigaux** [comment]
Please try branch "wip" . It should work.
Can you confirm?
Nb : to do: handle credit cards

**Comment by testcocoon** [comment]
No the wip branch does not help. The config was working since last week and the last commit on wip is too old to fix this new issue.

**Comment by prigaux** [comment]
Latest commit in wip is 3 hours ago!

**Comment by testcocoon** [comment]
Sorry, I my fault.
The WIP branch works better. I can get the amount of my current account.
The other accounts are no more listed (Livret A for example). I guess that this is due to the fact that they are moved to a dedicated web page.

**Comment by prigaux** [comment]
Hi, could you try latest wip? I've added support for credit cards and savings.
NB: you must adapt your code:

- Account "name" is now split into "name" and "owner"
- not all accounts are listed by default, so:
- use option "cb_accounts" if you want credit card accounts
- use option "all_accounts" if you want savings accounts

If it's ok for you, i'll release 8.00 to master branch.

**Comment by testcocoon** [comment]
It works but I have two warnings:
Argument "Pasd'op&eacute;ration sur ce compte." isn't numeric in
addition (+) at /usr/local/share/perl/5.20.2/Finance/Bank/LaPoste.pm
line 105.
Argument "Nature: Surisation" isn't numeric in addition (+) at
/usr/local/share/perl/5.20.2/Finance/Bank/LaPoste.pm line 105.

I set the parameters as followings:
my @accounts1 = Finance::Bank::LaPoste->check_balance(username =>
"XXXXX", password => "1234567", all_accounts => "true" );

Regards,
Sébastien

**Comment by prigaux** [comment]
I can silence the warning, but maybe there is something better to do. Any suggestion? Any missing information?

**Comment by testcocoon** [comment]
I will debug it this weekend and identify the line responsible of this
warning.

**Comment by testcocoon** [comment]
I just wanted to debug the warning issue and I discover that retrieving the data from the server of La Banque Postale does not work any more. I guess that they change again something...
Also, I saw an other issue: the list of transactions downloaded from the server was limited to 16 transactions.

**Comment by prigaux** [comment]
fixed in 8.01 !
