### ISSUE TITLE
Can't call method "statements" on an undefined value

### ISSUE THREAD

**Issue by loneept** [pixel/perl-finance-bank-laposte#8]
Hello,

It seems that the module is not working anymore, I'd say since the 14th of may 2020.

Here is the error returned : Can't call method "statements" on an undefined value

**Comment by prigaux** [comment]
Can you try https://github.com/pixel/perl-finance-bank-laposte/tree/wip ?

AFAIK it fixes another issue but I do not have the issue you have...

**Comment by loneept** [comment]
Thanks for your quick reply.

I believe I am already on this version (our $VERSION = '9.02';). FYI, this module has been working for me since 2016.

When I start the script, with just your example in it, and I put the right login / password, nothing happens (the script starts, finish, but nothing prints on the screen).
When I put a wrong login / password, here is what the script returns (I believe this is normal) :

getting https://transverse.labanquepostale.fr/voscomptes/canalXHTML/comptesCommun/synthese_ep/afficheSyntheseEP-synthese_ep.ea failed
<html>
<head><title>An Error Occurred</title></head>
<body>
<h1>An Error Occurred</h1>
<p>404 Not Found</p>
</body>
</html>


________________________________

**Comment by loneept** [comment]
My bad, it's working with the  https://github.com/pixel/perl-finance-bank-laposte/tree/wip

Thanks !!

________________________________

**Comment by prigaux** [comment]
Ok, i will release 9.03 soon. Thanks!

**Comment by prigaux** [comment]
9.03 released
